config/routes.rb
Rails.application.routes.draw do

  get 'posts/index'

  get 'posts/show'

  get 'posts/recommend' , to: 'posts#recommend'

  devise_for :users
    
  root to: 'posts#index'

  resources :posts, only:[:index, :show] do
    post 'like' => 'posts#like'
    resources :comments
  end

  namespace :admin do
    resources :users
    resources :posts do
      post 'recommend' => 'posts#set_recommend'
      post 'unrecommend' => 'posts#set_unrecommend'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :comments
    validates :title, presence: true

  def get_feature_pic
    @match = content.match(/<img.*?>/)
    if @match
      @match[0]
    else
      '<img src="/uploads/default.jpeg" alt="" />'
    end
  end

  def get_preview
    @str = content.gsub(/<\/?.*?>/,"")
    if @str.length > 200
      "#{@str[0,200]}......"
    else
      @str
    end
  end

  def get_views
    @view = view
    if @view == 0
      '0 view'
    else
      "#{@view} views"
    end
  end

  def get_comments
    @comment = comments.size
    if @comment == 0
      '0 comment'
    else
      "#{@comment} comments"
    end
  end

  def get_like
    @like = like
    if @like == 0
      '0 like'
    else
      "#{@like} likes"
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = ['admin', 'author']
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  validates :phone, :name, presence: true
  validates :phone, uniqueness: true
  validates :email, uniqueness: true, unless: "email.blank?"

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.phone || self.email
  end

  def active_for_authentication?
    active
  end

  def admin?
    role == 'admin'
  end

  def email_required?
    false
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(phone) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'back_office'
  before_action :authenticate_user!
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  include ResourceControllerMixin

  PAGE_SIZE = 20

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def set_recommend
    @recommend = Post.find(params[:post_id])
    @recommend.update(is_recommend: true)
    redirect_to admin_posts_path
  end

  def set_unrecommend
    @recommend = Post.find(params[:post_id])
    @recommend.update(is_recommend: false)
    redirect_to admin_posts_path
  end
  private
  def set_dirs
    @dir1 = 'posts'
  end

  def set_resource
    @post = Post.find(params[:id])
  end

  def resource
    @post
  end

  def build_resource
    @post = Post.new resource_params
  end

  def resource_params
    params.require(:post).permit(:title, :content)
  end

  def redirect_to_after_save
    [:admin, :posts]
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  include ResourceControllerMixin

  PAGE_SIZE = 20

  def index
    @users = User.where.not(id: 1)
  end

  def new
    @user = User.new
  end

  private
  def set_dirs
    @dir1 = 'users'
  end

  def set_resource
    @user = User.find(params[:id])
  end

  def resource
    @user
  end

  def build_resource
    @user = User.new resource_params
  end

  def resource_params
    params.require(:user).permit(:name, :phone, :email, :role, :password, :password_confirmation, :active)
  end  

  def redirect_to_after_save
    [:admin, :users]
  end  
end

app/controllers/app_controller.rb
class AppController < ActionController::Base
  def self.included(base)
    base.layout :"app"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include DeviseSupport
  
  before_action :set_dirs

  def set_dirs
    
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/devise_support.rb
module DeviseSupport
  
  def self.included(base)
    base.layout :layout_by_resource
    base.before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def layout_by_resource
    if devise_controller?
      "blank"
    else
      "application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :id_number

    devise_parameter_sanitizer.for(:sign_in) << :login
    # devise_parameter_sanitizer.for(:account_update) { |u|
    #   u.permit(:password, :password_confirmation, :current_password)
    # }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < AppController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @post.update(view: @post.view + 1)
  end

  def recommend
    @posts = Post.where("is_recommend = ?", true).order(created_at: :desc)
  end

  def like
    @like = Post.find(params[:post_id])
    @like.update(like: @like.like + 1)
    render json: {status:'success'}.to_json
  end
end

app/controllers/resource_controller_mixin.rb
module ResourceControllerMixin

  def self.included(base)
    base.before_action :set_resource, only: [:show, :edit, :update, :destroy, :recommend, :unrecommend, :activate, :inactivate]
  end

  def create
    @resource = build_resource
    if @resource.save
      redirect_to redirect_to_after_save
    else
      render action: 'new'
    end
  end

  def edit

  end

  def update
    resource.update(resource_params)
    if resource.save
      redirect_to redirect_to_after_save
    else
      render 'edit'
    end
  end

  def destroy
    resource.destroy
    redirect_to :back
  end

  def recommend
    resource.update_attribute(:recommended, true)
    render nothing: true
  end

  def unrecommend
    resource.update_attribute(:recommended, false)
    render nothing: true
  end

  def activate
    activated_at = resource.activated_at || Time.now
    resource.update_attributes active: true, activated_at: activated_at
    render nothing: true
  end

  def inactivate
    resource.update_attribute(:active, false)
    render nothing: true
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def index_of_item(current_index, page_size)
    page = params[:page] && params[:page].to_i-1 || 0
    current_index + page*page_size + 1
  end

  def active_for_dir1(dir1)
    'active' if dir1 == @dir1
  end

  def active_for_dir2(dir2)
    'active' if dir2 == @dir2
  end

  def active_for_dir3(dir3)
    'active' if dir3 == @dir3
  end

  def active_for_controllers(*ctrl_names)
    'active' if ctrl_names.include? controller_name
  end

  def active_for_actions(*action_names)
    'active' if action_names.include? action_name
  end

  def yes_or_no(bool)
    t("enum.#{!!bool}_value")
  end
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for [:admin, @post] do |f| %>
  <div class="col-sm-12">
    <div class="ibox float-e-margins">
      <div class="ibox-content">
        <%= f.input :title %>
        <%= f.input :content, :as => :kindeditor %>
        <%= f.association :tags, label_method: :tag, value_method: :id, class: 'select2', :input_html =>{ :multiple => 'multiple'} %>
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <button type="submit" class="btn btn-primary btn-block">提交</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% content_for :scripts do %>
    <script type="text/javascript">
        $("#post_tag_ids").select2({tag: true});
    </script>
<% end %>

app/views/admin/posts/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12 text-center">
    <h2>修改</h2>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row animated fadeInRight">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>文章管理</h2>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-title">
          <h5>文章列表</h5>
          <div class="ibox-tools">
            <%= link_to new_admin_post_path do %>
                <i class="fa fa-plus">新文章</i>
            <% end %>
          </div>
        </div>

        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table text-center table-striped table-hover">
              <thead>
              <tr>
                <td></td>
                <td>题目</td>
                <td>创建时间</td>
                <td>浏览次数</td>
                <td>操作</td>
              </tr>
              </thead>
              <tbody>
              <% @posts.each_with_index do |post, i| %>
                  <tr>
                    <td><%= i+1 %></td>
                    <td><%= post.title %></td>
                    <td><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                    <td><%= post.view %></td>
                    <td>
                      <%if post.is_recommend %>
                          <%= link_to '取消推荐', admin_post_unrecommend_path(post), method: 'post', class: 'btn btn-sm btn-success'%>
                      <%else%>
                          <%= link_to '推荐', admin_post_recommend_path(post), method: 'post', class: 'btn btn-sm btn-success'%>
                      <%end%>
                      <%= link_to '编辑', [:edit, :admin, post], class: 'btn btn-sm btn-warning' %>
                      <%= link_to '删除', [:admin, post], method: :delete, data:{confirm: '确定删除文章吗？'}, class: 'btn btn-sm btn-danger' %>
                    </td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12 text-center">
    <h2>写文章</h2>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row animated fadeInRight">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @user] do |f| %>
  <div class="col-sm-6">
    <div class="ibox float-e-margins">
      <div class="ibox-content">
        <%= f.input :name %>
        <%= f.input :phone %>
        <%= f.input :email %>

        <% if @user.new_record? %>
          <%= f.input :role, collection: User::ROLES, include_blank: '请选择角色' %>
          <%= f.input :password %>
        <% end %>
        <%= f.input :active %>
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <button type="submit" class="btn btn-primary btn-block">保存修改</button>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12 text-center">
    <h2>修改用户信息</h2>
  </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row animated fadeInRight">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-4">
    <h2>用户管理</h2>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
      <div class="ibox-title">
        <h5>用户列表</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <%= link_to [:new, :admin, :user] do %>
            <i class="fa fa-plus"></i>
          <% end %>
        </div>
      </div>

        <div class="ibox-content">
          <div class="table-responsive">
            <table class="table text-center table-striped table-hover">
              <thead>
                <tr>
                  <td></td>
                  <td>姓名</td>
                  <td>电话</td>
                  <td>角色</td>
                  <td>操作</td>
                </tr>
              </thead>
              <tbody>
                <% @users.each_with_index do |user, i| %>
                  <tr>
                    <td><%= i+1 %></td>
                    <td><%= user.name %></td>
                    <td><%= user.phone %></td>
                    <td><%= user.role %></td>
                    <td>
                      <%= link_to '编辑', [:edit, :admin, user], class: 'btn btn-sm btn-warning' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sm-12 text-center">
    <h2>添加用户信息</h2>
  </div>
</div>

<div class="wrapper wrapper-content">
  <div class="row animated fadeInRight">
    <%= render 'form' %>
  </div>
</div>

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="text-center m-t-lg">
        <h1>QuickStep Solutions</h1>
        <small>Here we go !!!</small>
      </div>
    </div>
  </div>
</div>

app/views/layouts/app.html.erb
<!DOCTYPE html>
<html class=" js no-touch csstransitions">
  <head>
    <title>QuickStep Solutions</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag 'app' %>
    <%= javascript_include_tag 'app' %>
    
    <%= csrf_meta_tags %>
    <%= yield :scripts %>
  </head>
  <body class="">
  <div class="page-wrapper">
    <!--header-->
    <%= cell('layout').(:app_header) %>

    <%= yield %>


    <%= cell('layout').(:app_sidebar) %>
  </div>
  </div>
  </section>
    <!--footer-->
    <%= cell('layout').(:app_footer) %>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuickStep Solutions</title>
  
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= yield :scripts %>
  </head>
  <body>
    <!-- Wrapper-->
    <div id="wrapper">
      <!-- Navigation -->
      <%= cell('layout').(:left) %>
      <!-- Page wraper -->
      <div id="page-wrapper" class="gray-bg">
        <!-- Page wrapper -->
        <%= cell('layout').(:top) %>
        <!-- Main view  -->
        <%= yield %>
        <!-- Footer -->
        <%= cell('layout').(:footer) %>
      </div>
      <!-- End page wrapper-->
    </div>
    <!-- End wrapper-->
    
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
  </body>
</html>

app/views/layouts/back_office.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>QuickStep Solutions</title>
  
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Wrapper-->
    <div id="wrapper">
      <!-- Navigation -->
      <%= cell('layout').(:left, @dir1, @dir2) %>
      <!-- Page wraper -->
      <div id="page-wrapper" class="gray-bg">
        <!-- Page wrapper -->
        <%= cell('layout').(:top) %>
        <!-- Main view  -->
        <%= yield %>
        <!-- Footer -->
        <%= cell('layout').(:footer) %>
      </div>
      <!-- End page wrapper-->
    </div>
    <!-- End wrapper-->
    
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.js") %>
    <%= yield :scripts %>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickStep Solutions</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <%= csrf_meta_tags %>
  </head>
  <body class="gray-bg">
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section class="main-container">

  <div class="container">
    <div class="row">

      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-8">
        <% @posts.each do |post| %>
        <!-- blogpost start -->
            <article class="blogpost">
              <div class="overlay-container">
                <%= post.get_feature_pic.html_safe%>
                <a class="overlay-link" href="<%= post_path(post) %>"><i class="fa fa-link"></i></a>
              </div>
              <header>
                <h2><%= link_to post.title,[post]%></h2>
                <div class="post-info">
										<span class="post-date">
											<i class="fa fa-calendar"></i>
											<span class="day"><%= post.created_at.strftime("%d %b %Y") %></span>
										</span>
                  <span class="submitted"><i class="fa fa-eye"></i> <%= post.get_views %></span>
                  <span class="comments"><i class="fa fa-comment"></i><%= post.get_comments%></span>
                </div>
              </header>
              <div class="blogpost-content">
                <p> <%= post.get_preview.html_safe %></p>
              </div>
              <footer class="clearfix">
                <div class="tags pull-left"><i class="fa fa-tags"></i> <a href="#">tag 1</a>, <a href="#">tag 2</a>, <a href="#">long tag 3</a></div>
                <div class="link pull-right"><i class="fa fa-arrow-circle-right"></i><a href="<%= post_path(post) %>">Read More</a></div>
              </footer>
            </article>
        <!-- blogpost end -->
        <% end %>

        <!--&lt;!&ndash; pagination start &ndash;&gt;-->
        <!--<nav>-->
          <!--<ul class="pagination">-->
            <!--<li><a href="#" aria-label="Previous"><i class="fa fa-angle-left"></i></a></li>-->
            <!--<li class="active"><a href="#">1</a></li>-->
            <!--<li><a href="#">2</a></li>-->
            <!--<li><a href="#">3</a></li>-->
            <!--<li><a href="#">4</a></li>-->
            <!--<li><a href="#">5</a></li>-->
            <!--<li><a href="#" aria-label="Next"><i class="fa fa-angle-right"></i></a></li>-->
          <!--</ul>-->
        <!--</nav>-->
        <!--&lt;!&ndash; pagination end &ndash;&gt;-->

      </div>
      <!-- main end -->

app/views/posts/recommend.html.erb
<section class="main-container">

  <div class="container">
    <div class="row">

      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-8">
        <% @posts.each do |post| %>
        <!-- blogpost start -->
            <article class="blogpost">
              <div class="overlay-container">
                <%= post.get_feature_pic.html_safe%>
                <a class="overlay-link" href="<%= post_path(post) %>"><i class="fa fa-link"></i></a>
              </div>
              <header>
                <h2><%= link_to post.title,[post]%></h2>
                <div class="post-info">
										<span class="post-date">
											<i class="fa fa-calendar"></i>
											<span class="day"><%= post.created_at.strftime("%d %b %Y") %></span>
										</span>
                  <span class="submitted"><i class="fa fa-spinner"></i> <%= post.get_views %></span>
                  <span class="comments"><i class="fa fa-comment"></i><%= post.get_comments%></span>
                </div>
              </header>
              <div class="blogpost-content">
                <p> <%= post.get_preview.html_safe %></p>
              </div>
              <footer class="clearfix">
                <div class="tags pull-left"><i class="fa fa-tags"></i> <a href="#">tag 1</a>, <a href="#">tag 2</a>, <a href="#">long tag 3</a></div>
                <div class="link pull-right"><i class="fa fa-arrow-circle-right"></i><a href="<%= post_path(post) %>">Read More</a></div>
              </footer>
            </article>
        <!-- blogpost end -->
        <% end %>

        <!--&lt;!&ndash; pagination start &ndash;&gt;-->
        <!--<nav>-->
          <!--<ul class="pagination">-->
            <!--<li><a href="#" aria-label="Previous"><i class="fa fa-angle-left"></i></a></li>-->
            <!--<li class="active"><a href="#">1</a></li>-->
            <!--<li><a href="#">2</a></li>-->
            <!--<li><a href="#">3</a></li>-->
            <!--<li><a href="#">4</a></li>-->
            <!--<li><a href="#">5</a></li>-->
            <!--<li><a href="#" aria-label="Next"><i class="fa fa-angle-right"></i></a></li>-->
          <!--</ul>-->
        <!--</nav>-->
        <!--&lt;!&ndash; pagination end &ndash;&gt;-->

      </div>
      <!-- main end -->

app/views/posts/show.html.erb
<section class="main-container">

  <div class="container">
    <div class="row">

      <!-- main start -->
      <!-- ================ -->
      <div class="main col-md-8">

        <!-- page-title start -->
        <!-- ================ -->
        <h1 class="page-title"><%= @post.title %></h1>
        <!-- page-title end -->

        <!-- blogpost start -->
        <!-- ================ -->
        <article class="blogpost full">
          <header>
            <div class="post-info">
										<span class="post-date">
											<i class="fa fa-calendar"></i>
											<span class="day"><%= @post.created_at.strftime("%d %b %Y") %></span>
										</span>
              <span class="submitted"><i class="fa fa-eye"></i> <%= @post.get_views %></span>
              <span class="comments"><i class="fa fa-comment"></i><%= @post.get_comments%></span>
            </div>
          </header>
          <div class="blogpost-content">
            <p><%= @post.content.html_safe %></p>
          </div>
          <footer class="clearfix">
            <div class="tags pull-left"><i class="icon-tags"></i> <a href="#">tag 1</a>, <a href="#">tag 2</a>, <a href="#">long tag 3</a></div>
            <div class="link pull-right">
              <ul class="social-links circle small colored clearfix margin-clear text-right animated-effect-1">
                <li class="twitter"><a id="likelink" href="javascript:void(0)" onclick="faclick()"><i id = "like" class="fa fa-heart-o"></i></a></li>
              </ul>
              <span id="likenum"><%= @post.get_like %></span>
            </div>
          </footer>
        </article>
        <!-- blogpost end -->

        <!-- comments start -->
        <!-- ================ -->
        <div id="comments" class="comments">
          <h2 class="title">评论</h2>
          <% @post.comments.each do |c| %>
          <!-- comment start -->
          <div class="comment clearfix">
            <!--<div class="comment-avatar">-->
              <!--<img class="img-circle" src="images/avatar.jpg" alt="avatar">-->
            <!--</div>-->
            <header>
              <h3><%= c.commenter %></h3>
              <div class="comment-meta"></div>
            </header>
            <div class="comment-content">
              <div class="comment-body clearfix">
                <%= c.body %>
              </div>
            </div>
          </div>
          <!-- comment end -->
          <% end %>
        </div>
        <!-- comments end -->

        <!-- comments form start -->
        <!-- ================ -->
        <%= simple_form_for([@post, @post.comments.build]) do |f| %>
        <div class="comments-form">
          <h2 class="title">添加评论</h2>
            <div class="form-group has-feedback">
              <%= f.text_field :commenter, class: "form-control" %>
            </div>
            <div class="form-group has-feedback">
              <%= f.text_area :body, class: "form-control" %>
            </div>
          <button type="submit" class="btn btn-primary btn-block">提交</button>
          </form>

        </div>
          <% end %>
        <!-- comments form end -->
      </div>
      <!-- main end -->
<% content_for :scripts do %>
    <script type="text/javascript">
      function faclick() {
          $.ajax(
                  {
                      url: '<%= post_like_path(@post) %>',
                      type: "post",
//                      error: function () {
//                          alert("出错:-(");
//                      },
                      success: function (data) {
                          if(data.status) {
                              $("#like").removeClass("fa-heart-o")
                              $("#like").addClass("fa-heart");
                              var like = $("#likenum").html();
                              like = Number(like.replace(/[^0-9]/ig,"")) + 1;
                              $("#likenum").text(like+" likes");
                              $("#likelink").removeAttr("onclick");

                          }
                      }
                  }
          );
      }
    </script>
<% end %>